### ISSUE TITLE
Wrong array typing 

### ISSUE THREAD

**Issue by lopi-py** [csqrl/sift#10]
Hi I'm using rbxts, and Array.join/aliases returns a wrong type, look
```ts
const arr1 = ["a", "b", "c"];
const arr2 = ["d", "e", "f"];
const result = Sift.Array.join(arr1, arr2);
```
the type return should be `string[]` but I get `string[][]` and thats wrong.

I think this could fix it:
```ts
function concat<T>(...arrays: T[]): T; // remove [] in return type
```

**Comment by csqrl** [comment]
thanks. I'll look into this! please let me know if you find any more
