### ISSUE TITLE
Improper handling of holes in arguments

### ISSUE THREAD

**Issue by Reselim** [csqrl/sift#3]
See: https://github.com/freddylist/llama/pull/3

It looks like handling of holes is intentional by [the type signature](https://github.com/csqrl/sift/blob/main/src/Dictionary/merge.lua#L27), but because it uses `ipairs`, holes aren't supported. May need to switch to using `select` for tuples, as the `#` operator doesn't work for lists with holes, IIRC.

**Comment by csqrl** [comment]
I noticed this myself the other day. Will issue a fix for this soon! 😊
