### ISSUE TITLE
Add Set difference functions

### ISSUE THREAD

**Issue by LouieK22** [csqrl/sift#9]
I am willing to implement this feature, just want to open an issue for discussion and approval first 😄 

Proposal:
```lua
local bobsPets = {
    cat = true,
    dog = true,
    bird = true,
}

local timsPets = {
    bird = true,
    snake = true,
    spider = true,
}

-- Asymmetric Difference
Sift.Set.difference(bobsPets, timsPets) -- { cat, dog }
Sift.Set.difference(timsPets, bobsPets) -- { snake, spider }

-- Symmetric Difference
Sift.Set.symmetricDifference(bobsPets, timsPets) -- { cat, dog, snake, spider }
Sift.Set.symmetricDifference(timsPets, bobsPets) -- { cat, dog, snake, spider }
```

**Comment by csqrl** [comment]
Seems like a useful addition to sets! It might be worth adding something like this to arrays too.

I quickly threw together this implementation on my phone while I'm unable to access my PC. Is this more or less what you were aiming for?

https://gist.github.com/csqrl/83ec9784a6714c3c5b767a9bc9cb3b8b#file-difference-sift-lua
